### ISSUE TITLE
exclude mirrors

### ISSUE THREAD

**Issue by dotysan** [hrbrmstr/pypi-malicious-packages#1]
Since they aren't really tyops.

```
AND details.installer.name NOT IN ('bandersnatch')
```

For that matter, could also exclude browsers.

```
AND details.installer.name NOT IN ('bandersnatch', 'Browser')
```

**Comment by hrbrmstr** [comment]
I'm not following "not really typos" and why wld a d/l via browser mean the use was safe?

**Comment by dotysan** [comment]
Bandersnatch downloads aren't really installed anywhere. Just automatically copied to another mirror. Thus your graphs have lots of activity at the beginning right after the package is uploaded. This doesn't represent someone actually installing it.

As for Browser downloads, I'm only guessing. Maybe some are manually installed.

**Comment by hrbrmstr** [comment]
gotcha. thx. will re-run the queries.
